# Tutorials on using Meteor Package to solve quantum problems
- Simulation of Boson sampling
- Simulation of quantum circuit
- Simulation of variational quantum circuit

## Part 1: Simulation of Boson sampling

Pipeline for boson sampling simulation:
- Generating initial separable quantum state
- Generating an optical circuit from phase shifters and beam spliters
- Applying the optical circuit onto the quantum state and obtaining amplitudes 

In [1]:
push!(LOAD_PATH, "../../src")

using Meteor.TensorNetwork
using Meteor.OpticalCircuit
using Meteor.OpticalCircuit.Utility

# Generating an initial state

L = 6
N = div(L, 2)
d = N+1
depth = L

initial_state = [0 for _ in 1:L]
initial_state[1:N] .= 1

# random basis generate 10 random basis with L modes, N particles, and a maximum of d-1 particles per mode
basis = randombasis(L, d, N, 10)

10-element Array{Array{Int64,1},1}:
 [2, 0, 0, 0, 0, 1]
 [1, 0, 0, 0, 0, 2]
 [0, 0, 2, 0, 1, 0]
 [2, 0, 0, 1, 0, 0]
 [0, 0, 1, 2, 0, 0]
 [0, 1, 1, 0, 0, 1]
 [0, 0, 0, 0, 3, 0]
 [0, 0, 0, 2, 1, 0]
 [0, 1, 0, 0, 1, 1]
 [2, 0, 0, 0, 1, 0]

In [2]:
# generating random bosonic circuit

using LinearAlgebra: I
function generate_boson_circuit_with_U(L::Int, N::Int, depth::Int)
    circuit = BosonCircuit(N)
    U = Matrix{ComplexF64}(I, L, L)
    for i = 1:L
        phi = rand(Float64)
        add_phase_shifter!(circuit, i, phi)
        U = phase_shifter_matrix(phi, L, i) * U
    end
    for d = 0:(depth-1)
        if d % 2 ==0
            for i = 1:2:(L-1)
                theta = rand(Float64)
                add_beam_spliter!(circuit, (i, i+1), theta)
                U = beam_spliter_matrix(theta, L, (i, i+1)) * U
            end
            for i = 1:2:(L-1)
                phi = rand(Float64)
                add_phase_shifter!(circuit, i, phi)
                U = phase_shifter_matrix(phi, L, i) * U
            end
        else
            for i = 2:2:(L-1)
                theta = rand(Float64)
                add_beam_spliter!(circuit, (i, i+1), theta)
                U = beam_spliter_matrix(theta, L, (i, i+1)) * U
            end
            for i = 2:2:(L-1)
                phi = rand(Float64)
                add_phase_shifter!(circuit, i, phi)
                U = phase_shifter_matrix(phi, L, i) * U
            end
        end
    end
    return circuit, U
end


circuit, U = generate_boson_circuit_with_U(L, N, depth)
println("number of gate operations $(length(circuit)).")

number of gate operations 36.


### Random optical circuit generated above ![BosonSampling](bosonsampling.png)

### First approach to compute amplitudes-evolving the state to get a final state, and then perform measurement

In [3]:
using LinearAlgebra: dot

state = complex(product_state(circuit, initial_state))
apply!(circuit, state)

# measure amplitude one by one
amps = [dot(state, product_state(circuit, item)) for item in basis]

10-element Array{Complex{Float64},1}:
  -0.09519232533710721 + 0.09464917451511544im
 -0.003505808167463626 + 0.0008299326516810119im
 -0.012728054920145516 - 0.0290103210262253im
   0.14111404070102243 + 0.06710697032116664im
  -0.06865312035642993 + 0.1437559378217299im
 -0.010168914401645865 + 0.033125723127067894im
  -0.07641172237495361 + 0.026431475459560847im
    0.2985172758287943 + 0.025056498792779585im
  -0.07288641322837265 + 0.17876282183533082im
  -0.11298456465933826 - 0.10652624197235304im

One can obtain additional information since the final state has been stored-entropy production example

In [4]:
# get the entropy from the final state
using Meteor.Tensor: entropy

etps = entropy.(svectors(state))

7-element Array{Float64,1}:
 -0.0
  1.1333353726877304
  1.8291788236321609
  1.9171276987356345
  1.451043944785007
  0.6233419201809652
 -0.0

### Second approach to compute amplitudes-directly performing measurement, more efficiently if only a few number of amplitudes are to be computed

In [5]:
amps = amplitudes(circuit, initial_state, basis, scaling=1.)

10-element Array{Complex{Float64},1}:
  -0.09519232533710725 - 0.0946491745151155im
 -0.003505808167463647 - 0.000829932651681019im
 -0.012728054920145488 + 0.029010321026225288im
    0.1411140407010225 - 0.06710697032116669im
  -0.06865312035642991 - 0.14375593782172968im
 -0.010168914401645893 - 0.033125723127067894im
  -0.07641172237495351 - 0.026431475459560826im
   0.29851727582879384 - 0.025056498792779564im
  -0.07288641322837269 - 0.17876282183533096im
   -0.1129845646593382 + 0.10652624197235308im

### Comparison with permanent

In [6]:
amp1s = ComplexF64[]
amp2s = ComplexF64[]
for item in basis
    amp1 = amplitude(circuit, initial_state, item, scaling=1.)
    
    m = select_submatrix(item, U, initial_state)
    amp2 = permanent(m)
    push!(amp1s, amp1)
    push!(amp2s, amp2)
end

println("largest error between two approaches $(maximum(abs.(amp1s-amp2s))).")

largest error between two approaches 2.7336071744532853e-16.


## Part 2: Simulation of quantum circuit

Pipeline for quantum circuit simulation:
- Generating initial separable quantum state
- Generating a quantum circuit from phase shifters and beam spliters
- Applying quantum measurements

### A trivial example-bell state

In [7]:
using Meteor.QuantumCircuit

state = statevector(2)

circuit = QCircuit([HGate(1), CNOTGate(1,2)])

apply!(circuit, state)

# measuring amplitudes
println("the amplitude on [0,0] is $(amplitude(state, [0,0], scaling=1.)).")
println("the amplitude on [0,1] is $(amplitude(state, [0,1], scaling=1.)).")
println("the amplitude on [1,0] is $(amplitude(state, [1,0], scaling=1.)).")
println("the amplitude on [1,1] is $(amplitude(state, [1,1], scaling=1.)).")

# measuring each qubit
i, prob = measure!(state, 1)
println("the probability to obtain state $i for the 1-th qubit is $prob.")

the amplitude on [0,0] is 0.7071067811865475 + 0.0im.
the amplitude on [0,1] is 0.0 + 0.0im.
the amplitude on [1,0] is 0.0 + 0.0im.
the amplitude on [1,1] is 0.7071067811865475 + 0.0im.
the probability to obtain state 1 for the 1-th qubit is 0.4999999999999999.


### Understand the QuantumCircuit module in depth
Different backend with almost the same interface
- Store the state vector in a brute-force way, exponential scaling $2^n$ with number of qubits, suitable for very deep circuit with number of qubits less than $36$ 
- Store the state vector using matrix product states (MPS), scaling $2n D^2$, where the **bond dimension** $D$ is related with the bipartition entropy, suitable for circuit which will only generate relativelly low entanglement, such as shallow quantum circuit
- Schodinger-Feymann simulator, splitting $n$ qubits into two parts with two brute-force simulator, suitable for quantum circuit which could be divided into two separate circuits by **cutting** only a few cross gates
- Projected entangled pair states (PEPS), used for quantum circuit on an arbitrary graph, with realtively low circuit depth

Example with two-dimensional random quantum circuit

### Introduction to Random Quantum Circuits
    
1. Finding a problem which is very hard to solve with the best supercomputer in the world, but can be efficiently solved with a quantum computer.
2. Random quantum circuit (**RQCs**) sampling problem is a standard problem used to demonstrate quantum supremacy in near term.
3. We propose to use Projected Entangled Pair States (**PEPS**) to study large-scale RQCs.

The random quantum circuit proposed in [Characterizing Quantum Supremacy in Near-Term Devices](arXiv:1608.00263v3)
![google circuit](GoogleCircuitH.png)

Rules for $L_h\times L_v$ circuit:
1. Apply a Hadamard gate to each qubit to initialize the qubits to a symmetric superposition.
2. Apply controlled-phase (CZ) gates alternating between $8$ configurations as above entangle neighbouring qubits.
3. Apply a randomly chosen gate ($T$, $\sqrt{X}$ or $\sqrt{Y}$) to each qubit on which the CZ gates has not just been applied, according to certain rules.
4. Repeat steps 2 and 3 to add layers of depth to the circuit.
5. Apply a final Hadamard gate to each qubit.

In [8]:
# Genertae an m * n random quantum circuit with depth d
function google_circuit(m::Int, n::Int, depth::Int)
    XYT = Dict(0=>sqrtX, 1=>sqrtY, 2=>T)
    Xoperated = zeros(Bool, m, n)
    Yoperated = zeros(Bool, m, n)
    Toperated = zeros(Bool, m, n)
    CZoperated = zeros(Bool, m, n)

    ControlZ = CZ
    config1 = []
    config2 = []
    config3 = []
    config4 = []
    config5 = []
    config6 = []
    config7 = []
    config8 = []
    config1sites = []
    config2sites = []
    config3sites = []
    config4sites = []
    config5sites = []
    config6sites = []
    config7sites = []
    config8sites = []
    toind(i,j) = linear_index((m, n), (i, j), false)

    # 1 configuration
    for jj in 0:2:(n-2)
        for ii in ((div(jj,2)+1)%2):2:(m-1)
            i = ii + 1
            j = jj + 1
            push!(config1, ((toind(i, j), toind(i, j+1)), ControlZ))
            push!(config1sites, (i, j))
            push!(config1sites, (i, j+1))
        end
    end

    # 2 configuration
    for jj in 0:2:(n-2)
        for ii in ((div(jj,2))%2):2:(m-1)
            i = ii + 1
            j = jj + 1
            push!(config2, ((toind(i, j), toind(i, j+1)), ControlZ))
            push!(config2sites, (i, j))
            push!(config2sites, (i, j+1))
        end
    end

    # 5 configuration
    for jj in 1:2:(n-2)
        for ii in ((div(jj,2)+1)%2):2:(m-1)
            i = ii + 1
            j = jj + 1
            push!(config5, ((toind(i, j), toind(i, j+1)), ControlZ))
            push!(config5sites, (i, j))
            push!(config5sites, (i, j+1))
        end
    end

    # 6 configuration
    for jj in 1:2:(n-2)
        for ii in (((div(jj,2)))%2):2:(m-1)
            i = ii + 1
            j = jj + 1
            push!(config6, ((toind(i, j), toind(i, j+1)), ControlZ))
            push!(config6sites, (i, j))
            push!(config6sites, (i, j+1))
        end
    end

    # 3 configuration
    for ii in 1:2:(m-2)
        for jj in ((div(ii,2)+1)%2):2:(n-1)
            i = ii + 1
            j = jj + 1
            push!(config3, ((toind(i, j), toind(i+1, j)), ControlZ))
            push!(config3sites, (i, j))
            push!(config3sites, (i+1, j))
        end
    end

    # 4 configuration
    for ii in 1:2:(m-2)
        for jj in ((div(ii,2))%2):2:(n-1)
            i = ii + 1
            j = jj + 1
            push!(config4, ((toind(i, j), toind(i+1, j)), ControlZ))
            push!(config4sites, (i, j))
            push!(config4sites, (i+1, j))
        end
    end

    # 7 configuration
    for ii in 0:2:(m-2)
        for jj in ((div(ii,2))%2):2:(n-1)
            i = ii + 1
            j = jj + 1
            push!(config7, ((toind(i, j), toind(i+1, j)), ControlZ))
            push!(config7sites, (i, j))
            push!(config7sites, (i+1, j))
        end
    end

    # 8 configuration
    for ii in 0:2:(m-2)
        for jj in ((div(ii,2)+1)%2):2:(n-1)
            i = ii + 1
            j = jj + 1
            push!(config8, ((toind(i, j), toind(i+1, j)), ControlZ))
            push!(config8sites, (i, j))
            push!(config8sites, (i+1, j))
        end
    end

    configs=[(config1, config1sites), (config2, config2sites), (config3, config3sites),
        (config4, config4sites), (config5, config5sites), (config6, config6sites),
        (config7, config7sites), (config8, config8sites)]

    function __generate_one_body_gates()
        one_body_gates = []
        tmpXoperated = zeros(Bool, m, n)
        tmpYoperated = zeros(Bool, m, n)
        for i in 1:m
            for j in 1:n
                # Place a gate at qubit q only if this qubit is
                # occupied by a CZ gate in the previous cycle
                if CZoperated[i, j]
                    # Place a T gate at qubit q if there are no single
                    # qubit gates in the previous cycles at qubit q except
                    # for the initial cycle of Hadamard gates
                    if !Toperated[i, j]
                        push!(one_body_gates, (toind(i, j), XYT[2]))
                        Toperated[i, j] = true
                    else
                        # Any gate at qubit q should be different from
                        # the gate at qubit q in the previous cycle.
                        if tmpXoperated[i, j]
                            push!(one_body_gates, (toind(i, j), XYT[1]))
                            tmpYoperated[i, j] = true
                        else
                            if tmpYoperated[i, j]
                                push!(one_body_gates, (toind(i, j), XYT[0]))
                                tmpXoperated[i, j] = true
                            else
                                r = rand(0:1)
                                push!(one_body_gates, (toind(i, j), XYT[0]))
                                if r == 0
                                    tmpXoperated[i, j] = true
                                else
                                    tmpYoperated[i, j] = true
                                end
                            end
                        end
                    end
                end
            end
        end
        Xoperated = tmpXoperated
        Yoperated = tmpYoperated
        return one_body_gates
    end


    circuit = QCircuit()
    for i in 1:m
        for j in 1:n
            push!(circuit, (toind(i, j), H))
        end
    end
    for i in 0:(depth-1)
        present_config = i % 8 + 1
        # println("present config is $present_config")
        config, configsites = configs[present_config]
        fill!(CZoperated, false)
        for item in configsites
            CZoperated[item...] = true
        end
        one_body_gates = __generate_one_body_gates()
        for item in one_body_gates
            push!(circuit, item)
        end
        for item in config
            push!(circuit, item)
        end
        # append!(circuit, one_body_gates)
        # append!(circuit, config)
    end
    for i in 1:m
        for j in 1:n
            push!(circuit, (toind(i, j), H))
        end
    end
    return circuit
end

google_circuit (generic function with 1 method)

In [9]:
m = 5
n = 5
depth = 8

circuit = google_circuit(m, n, depth)
println("number of gate operations $(length(circuit)).")

number of gate operations 170.


### Gate fusion technique-absorbing onebody gate into twobody gate

In [10]:
circuit = fuse_gate(circuit)
println("number of gate operations after gate fusion $(length(circuit)).")

number of gate operations after gate fusion 40.


### Brute-force simulator

In [11]:
state = statevector(ComplexF32, m * n)

# generating random basis
basis = [rand(0:1, m*n) for _ in 1:5]
apply!(circuit, state)

amps = amplitudes(state, basis, scaling=sqrt(2))

5-element Array{Complex{Float64},1}:
 -0.7212962763810143 + 0.13179740997841694im
 0.19600240171336664 - 0.1698445713143836im
  0.8347877927646036 - 0.35937513477808414im
 0.11316624808020642 + 0.2511107126936645im
  0.9590029846959107 + 0.155464846319164im

### Matrix Product States Simulator

In [12]:
state = qstate(m * n)

apply!(circuit, state)
amps = amplitudes(state, basis, scaling=sqrt(2))

5-element Array{Complex{Float64},1}:
 -0.7212961078734764 + 0.13179732566475474im
 0.19600243558256952 - 0.16984465132951im
   0.834787607362388 - 0.35937499999999195im
 0.11316626073623946 + 0.2511104345603936im
  0.9590024115546597 + 0.15546480419227132im

### Schodinger-Feymann simulator

In [13]:
half_position = div(m * n, 2)
sf_circuit = SFQCircuit(ComplexF32, collect(1:half_position), collect(half_position+1:m*n), circuit, verbose=2)
amps = amplitudes(state, basis, scaling=sqrt(2))

a wedge (12, 13), (12, 17) is found, with 4 branches.


5-element Array{Complex{Float64},1}:
 -0.7212961078734764 + 0.13179732566475474im
 0.19600243558256952 - 0.16984465132951im
   0.834787607362388 - 0.35937499999999195im
 0.11316626073623946 + 0.2511104345603936im
  0.9590024115546597 + 0.15546480419227132im

### PEPS simulator

Specifying the graph connectivity

In [14]:
connectivity = square_connectivity(m, n)
println(connectivity)

[(1, 2), (2, 3), (3, 4), (4, 5), (6, 7), (7, 8), (8, 9), (9, 10), (11, 12), (12, 13), (13, 14), (14, 15), (16, 17), (17, 18), (18, 19), (19, 20), (21, 22), (22, 23), (23, 24), (24, 25), (1, 6), (2, 7), (3, 8), (4, 9), (5, 10), (6, 11), (7, 12), (8, 13), (9, 14), (10, 15), (11, 16), (12, 17), (13, 18), (14, 19), (15, 20), (16, 21), (17, 22), (18, 23), (19, 24), (20, 25)]


In [15]:
gf_state = GraphState(ComplexF32, connectivity)

GraphState{Complex{Float32}}({25, 40} undirected simple Int64 graph, IndexedTensor{Complex{Float32},N} where N[IndexedTensor{Complex{Float32},3}(Complex{Float32}[1.0f0 + 0.0f0im; 0.0f0 + 0.0f0im], (1, 2, 3)), IndexedTensor{Complex{Float32},4}(Complex{Float32}[1.0f0 + 0.0f0im; 0.0f0 + 0.0f0im], (4, 2, 5, 6)), IndexedTensor{Complex{Float32},4}(Complex{Float32}[1.0f0 + 0.0f0im; 0.0f0 + 0.0f0im], (7, 5, 8, 9)), IndexedTensor{Complex{Float32},4}(Complex{Float32}[1.0f0 + 0.0f0im; 0.0f0 + 0.0f0im], (10, 8, 11, 12)), IndexedTensor{Complex{Float32},3}(Complex{Float32}[1.0f0 + 0.0f0im; 0.0f0 + 0.0f0im], (13, 11, 14)), IndexedTensor{Complex{Float32},4}(Complex{Float32}[1.0f0 + 0.0f0im; 0.0f0 + 0.0f0im], (15, 3, 16, 17)), IndexedTensor{Complex{Float32},5}(Complex{Float32}[1.0f0 + 0.0f0im; 0.0f0 + 0.0f0im], (18, 6, 16, 19, 20)), IndexedTensor{Complex{Float32},5}(Complex{Float32}[1.0f0 + 0.0f0im; 0.0f0 + 0.0f0im], (21, 9, 19, 22, 23)), IndexedTensor{Complex{Float32},5}(Complex{Float32}[1.0f0 + 0.0f0

In [16]:
apply!(circuit, gf_state)

amps = amplitudes(gf_state, basis, scaling=sqrt(2))

5-element Array{Complex{Float32},1}:
 -0.72129774f0 + 0.13179678f0im
  0.19600302f0 - 0.16984539f0im
   0.8347877f0 - 0.35937488f0im
  0.11316672f0 + 0.25111195f0im
  0.95900494f0 + 0.15546587f0im

Directly computing the amplitudes without store the final state, which maybe faster. Moreover, to get the best performance from the PEPS simulator, one needs to understand more about the problem to feed other keyword arguments into the function

In [17]:
amps = graph_amplitudes(ComplexF32, connectivity, circuit, basis, scaling=sqrt(2))

5-element Array{Complex{Float32},1}:
 -0.72129667f0 + 0.1317971f0im
  0.19600302f0 - 0.16984557f0im
  0.83478826f0 - 0.35937542f0im
  0.11316638f0 + 0.2511116f0im
   0.9590033f0 + 0.1554653f0im

## Part 3: Simulation of variational quantum circuit
Only brute-force and MPS simulator support automatic differentiation of variational quantum circuit currently

### Specifying a parameteric quantum gate-Variable wrapper

In [18]:
using Meteor.Diff

# This is a normal quantum gate
gate1 = RxGate(1, 0.5)
println("number of parameters $(nparameters(gate1)).")

# This is a variational quantum gate
gate2 = RxGate(1, Variable(0.5))
println("number of parameters $(nparameters(gate2)).")

# This is a variational two qubit gate
gate3 = CRxGate((1, 3), Variable(0.5))
println("number of parameters $(nparameters(gate3)).")

gate4 = CRxGate(control=1, target=3, theta=Variable(0.5))
println("number of parameters $(nparameters(gate4)).")

number of parameters 0.
number of parameters 1.
number of parameters 1.
number of parameters 1.


### A parameteric quantum circuit is just a quantum circuit with some parameteric quantum gates

In [19]:
# This is a normal quantum gate
gate1 = RxGate(1, Variable(0.5))

# This is a variational quantum gate
gate2 = CNOTGate(control=1,target=1)

circuit = QCircuit([gate1, gate2])
println(nparameters(circuit))

1


### A trivial example

In [20]:
L = 4
depth = 3

circuit = QCircuit()

for d in 1:depth
  for i in 1:L
    push!(circuit, RzGate(i, Variable(randn())))
    push!(circuit, RxGate(i, Variable(randn())))
    push!(circuit, RzGate(i, Variable(randn())))
  end
  for i in 1:L-1
    push!(circuit, CNOTGate(control=i, target=i+1))
  end
end

for i in 1:L
  push!(circuit, RzGate(i, Variable(randn())))
  push!(circuit, RxGate(i, Variable(randn())))
  push!(circuit, RzGate(i, Variable(randn())))
end

println("number of parameters $(nparameters(circuit)).")

# create an initial state [0,0,0,0,0]
state = qstate(L)

# A parameteric quantum circuit can be applied onto a quantum state just as a normal quantum state
apply!(circuit, state)

number of parameters 48.


9-element Array{Tuple{Int64,Float64},1}:
 (2, 0.0)
 (2, 0.0)
 (2, 0.0)
 (2, 0.0)
 (4, 0.0)
 (2, 0.0)
 (2, 0.0)
 (4, 0.0)
 (2, 0.0)

### Applying the quantum circuit onto the quantum state to produce an output quantum state, without changing the input state

In [21]:
state = qstate(L)
output_state = circuit * state

NSymMPS{Complex{Float64}}(Array{Complex{Float64},3}[[-0.7529462408962175 + 0.07608731232474654im 0.07084103722268449 - 0.4182440700745398im]

[0.23065020246636952 - 0.07702920270314918im -0.02333869304824819 - 0.43319558626109067im], [0.00142220498026846 - 0.7770926941294138im -0.503325451834151 - 0.07623767701359468im; 0.2352274393574406 + 0.06751991260872396im 0.3145708725953559 + 0.4495716800876567im]

[-0.09891287584411451 + 0.1169277535649978im -0.3261232178633932 + 0.02274724275337507im; -0.2450844935421836 + 0.4460896774129206im -0.5304051640877335 - 0.050977989071551294im]

[-0.021027545518920516 - 0.03641654501406166im 0.01569133867076337 + 0.006231172129343299im; 0.09111343183339873 - 0.16936983371186856im -0.22568674411678247 + 0.0010056384223976894im]

[-0.03663576083775663 + 0.022049227828990627im -0.000967321984118294 - 0.05257309379047611im; 0.07968494283847902 + 0.02312159370507103im 0.009907513723187487 + 0.033808403880946324im], [0.475919092969584 - 0.0500086675252595

### Create a loss function and compute the gradient

In [22]:
using Zygote

# Supported differential operations on quantum state: *, dot, distance
loss_example(circ) = begin
  out_put = circ * state
  return real(dot(out_put, state))
end


grad = parameters(gradient(loss_example, circuit))


48-element Array{Number,1}:
  0.08984941335422317
 -0.044103406631744765
  0.04934572237025491
  0.08984941335422321
 -0.07956824123472904
  0.03930939877787876
  0.08984941335422306
 -0.11446483496593426
  0.07075857830709727
  0.08984941335422314
 -0.02763835464121249
 -0.009040255174924555
  0.04934572237025489
  ⋮
  0.08106541499362216
  0.005901816962650097
  0.08984941335422314
  0.08985250816252767
 -0.20601982366124283
  0.08984941335422313
  0.08865991822062967
  0.05734994728616231
  0.08984941335422313
  0.09698598507231646
 -0.022293009236661436
  0.08984941335422315

### A complete example-quantum state tomography with variational quantum circuit

In [26]:
using Flux
using Flux.Optimise
using Meteor.Model: xxz, product_state!, ground_state!

function real_variational_circuit(L::Int, depth::Int)
    circuit = QCircuit()
    for i in 1:L
        add!(circuit, RyGate(i, Variable(randn(Float64))))
    end
    for i in 1:depth
        for j in 1:(L-1)
            add!(circuit, CNOTGate((j, j+1)))
        end
        for j in 1:L
            add!(circuit, RyGate(j, Variable(randn(Float64))))
        end
    end
    return circuit
end

function xxz_ground_state(L::Int, J::Real, Jzz::Real, h::Real)
    model = xxz(L, J=J, Jzz=Jzz, h=h)
    initial_state = [0 for i in 1:L]
    for i in 1:2:L
        initial_state[i] = 1
    end
    product_state!(model, initial_state)
    r = ground_state!(model, verbose=0)
    return model.state
end

L = 10
J = 1.
Jzz = 1.5
h = 0.1

initial_state = qstate(Float64, L)
target_state = xxz_ground_state(L, J, Jzz, h)

loss(circ) = 1 - abs(dot(target_state, circ * initial_state))

circuit = real_variational_circuit(L, depth)
x0 = parameters(circuit)

println("number of parameters $(length(x0)).")
opt = ADAM(0.05)

fvalues = [loss(circuit)]
for i in 1:200
    grad = parameters(gradient(loss, circuit))
    Optimise.update!(opt, x0, grad)
    set_parameters!(x0, circuit)
    ss = loss(circuit)
    push!(fvalues, ss)
    if i % 20 == 0
        println("loss at the $i-th step is $ss.")
    end
end


┌ Warning: no observers have been set.
└ @ Meteor.Model /Users/guochu/Documents/QuantumSimulator/Meteor.jl/src/Model/Model/base.jl:147


number of parameters 40.
loss at the 20-th step is 0.3554303430682362.
loss at the 40-th step is 0.0629559944071083.
loss at the 60-th step is 0.04316085652094115.
loss at the 80-th step is 0.03892008816773185.
loss at the 100-th step is 0.0361583733931391.
loss at the 120-th step is 0.03297106680166595.
loss at the 140-th step is 0.02968437060622653.
loss at the 160-th step is 0.027400013225553854.
loss at the 180-th step is 0.02642559056618321.
loss at the 200-th step is 0.0261336843227975.
